
name: .NET Core

on:

  push:
    branches: [ master ]
    paths-ignore: 
      - 'docs/**'
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'docs/**'
      - '**.md'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  buildJob:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        runtime: ["win-x86", "win-arm", "win-arm64", "win10-x64", "win10-x86", "win10-arm", "win10-arm64", "linux-x64", "linux-musl-x64", "linux-arm", "linux-arm64", "rhel-x64", "rhel.8-x64", "osx-x64", "osx.10.14-x64"]

    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow   

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.101

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
          versionSpec: '5.5.0'
        
    - name: Determine version
      uses: gittools/actions/gitversion/execute@v0.9.11
       
    - name: Display version
      run: |
       echo "SemVer: $GITVERSION_SEMVER"

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:AssemblyVersion=$GITVERSION_ASSEMBLYSEMFILEVER -p:FileVersion=$GITVERSION_ASSEMBLYSEMFILEVER -p:InformationalVersion=$GITVERSION_SEMVER

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish ${{ matrix.runtime }}
      run: dotnet publish .//SmartThingsTerminal//SmartThingsTerminal.csproj -o publish/v$GITVERSION_SEMVER/${{ matrix.runtime }} -c Release -r ${{ matrix.runtime }} -f net6.0 --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:IncludeNativeLibrariesForSelfExtract=true -p:AssemblyVersion=$GITVERSION_ASSEMBLYSEMFILEVER -p:FileVersion=$GITVERSION_ASSEMBLYSEMFILEVER -p:InformationalVersion=$GITVERSION_SEMVER

    - name: Zip ${{ matrix.runtime }} release
      run: 7z a ${{ matrix.runtime }}.zip ./publish/v${{ env.GITVERSION_SEMVER }}/${{ matrix.runtime }}/*

    - name: Release ${{ env.GITVERSION_SEMVER }}
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      with:
        files: |
          **.zip
        name: ${{ env.GITVERSION_SEMVER }}
        tag_name: ${{ env.GITVERSION_SEMVER }}


